# Generated by Django 4.2.2 on 2023-06-24 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadgranja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='descripcion',
        ),
    ]
