# Generated by Django 4.2.2 on 2023-06-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadgranja', '0002_remove_productos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='valor_producto',
            field=models.CharField(max_length=100, verbose_name='Valor'),
        ),
    ]
