# Generated by Django 4.2.2 on 2023-06-28 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadgranja', '0003_alter_productos_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='id_producto',
            new_name='id',
        ),
    ]
