# Generated by Django 4.2.2 on 2023-06-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadgranja', '0004_rename_id_producto_productos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(default=True, max_length=100, verbose_name='Descripcion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
