# Generated by Django 4.2.2 on 2023-06-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadgranja', '0005_productos_descripcion_productos_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(max_length=100, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
