# Generated by Django 4.2.2 on 2023-06-30 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoriaProduc', '0001_initial'),
        ('ciudadgranja', '0006_alter_productos_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='categorias',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categoriaProduc.categorias'),
        ),
    ]
